package replay

import (
	"fmt"
	"strings"
	"time"
)

// ExportToMarkdown exports a recording to Markdown format
func ExportToMarkdown(recording *Recording, events []*StreamEvent, report *AnalysisReport) (string, error) {
	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("# Execution Recording: %s\n\n", recording.ID))

	// Status badge
	statusIcon := "✅"
	switch recording.Status {
	case "failed":
		statusIcon = "❌"
	case "cancelled":
		statusIcon = "⚠️"
	}
	sb.WriteString(fmt.Sprintf("**Status:** %s %s\n\n", statusIcon, recording.Status))

	// Metadata table
	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Property | Value |\n")
	sb.WriteString("|----------|-------|\n")
	sb.WriteString(fmt.Sprintf("| Task ID | %s |\n", recording.TaskID))
	sb.WriteString(fmt.Sprintf("| Project | %s |\n", recording.ProjectPath))
	sb.WriteString(fmt.Sprintf("| Duration | %s |\n", formatDuration(recording.Duration)))
	sb.WriteString(fmt.Sprintf("| Events | %d |\n", recording.EventCount))
	sb.WriteString(fmt.Sprintf("| Started | %s |\n", recording.StartTime.Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("| Ended | %s |\n", recording.EndTime.Format("2006-01-02 15:04:05")))

	if recording.Metadata != nil {
		if recording.Metadata.Branch != "" {
			sb.WriteString(fmt.Sprintf("| Branch | `%s` |\n", recording.Metadata.Branch))
		}
		if recording.Metadata.CommitSHA != "" {
			sb.WriteString(fmt.Sprintf("| Commit | `%s` |\n", recording.Metadata.CommitSHA))
		}
		if recording.Metadata.PRUrl != "" {
			sb.WriteString(fmt.Sprintf("| PR | %s |\n", recording.Metadata.PRUrl))
		}
		if recording.Metadata.ModelName != "" {
			sb.WriteString(fmt.Sprintf("| Model | %s |\n", recording.Metadata.ModelName))
		}
		sb.WriteString(fmt.Sprintf("| Navigator | %v |\n", recording.Metadata.HasNavigator))
	}
	sb.WriteString("\n")

	// Token Usage
	if recording.TokenUsage != nil {
		sb.WriteString("## Token Usage\n\n")
		sb.WriteString(fmt.Sprintf("- **Input:** %s tokens\n", formatNumber(recording.TokenUsage.InputTokens)))
		sb.WriteString(fmt.Sprintf("- **Output:** %s tokens\n", formatNumber(recording.TokenUsage.OutputTokens)))
		sb.WriteString(fmt.Sprintf("- **Total:** %s tokens\n", formatNumber(recording.TokenUsage.TotalTokens)))
		sb.WriteString(fmt.Sprintf("- **Estimated Cost:** $%.4f\n", recording.TokenUsage.EstimatedCostUSD))
		sb.WriteString("\n")
	}

	// Phase Timing
	if report != nil && len(report.PhaseAnalysis) > 0 {
		sb.WriteString("## Phase Timing\n\n")
		sb.WriteString("| Phase | Duration | Percentage | Events |\n")
		sb.WriteString("|-------|----------|------------|--------|\n")
		for _, phase := range report.PhaseAnalysis {
			sb.WriteString(fmt.Sprintf("| %s | %s | %.1f%% | %d |\n",
				phase.Phase, formatDuration(phase.Duration), phase.Percentage, phase.EventCount))
		}
		sb.WriteString("\n")
	}

	// Tool Usage
	if report != nil && len(report.ToolUsage) > 0 {
		sb.WriteString("## Tool Usage\n\n")
		sb.WriteString("| Tool | Calls | Errors | Tokens |\n")
		sb.WriteString("|------|-------|--------|--------|\n")
		for _, tool := range report.ToolUsage {
			tokens := tool.InputTokens + tool.OutputTokens
			sb.WriteString(fmt.Sprintf("| %s | %d | %d | %s |\n",
				tool.Tool, tool.Count, tool.ErrorCount, formatNumber(tokens)))
		}
		sb.WriteString("\n")
	}

	// Errors
	if report != nil && len(report.Errors) > 0 {
		sb.WriteString("## Errors\n\n")
		for i, err := range report.Errors {
			sb.WriteString(fmt.Sprintf("### Error %d\n\n", i+1))
			sb.WriteString(fmt.Sprintf("- **Time:** %s (#%d)\n", err.Timestamp.Format("15:04:05"), err.Sequence))
			sb.WriteString(fmt.Sprintf("- **Phase:** %s\n", err.Phase))
			if err.Tool != "" {
				sb.WriteString(fmt.Sprintf("- **Tool:** %s\n", err.Tool))
			}
			sb.WriteString(fmt.Sprintf("- **Message:** `%s`\n\n", err.Message))
		}
	}

	// Event Log (condensed)
	sb.WriteString("## Event Timeline\n\n")
	sb.WriteString("<details>\n<summary>Click to expand event log</summary>\n\n")
	sb.WriteString("```\n")

	for _, event := range events {
		formatted := FormatEvent(event, false)
		sb.WriteString(formatted)
		sb.WriteString("\n")
	}

	sb.WriteString("```\n\n")
	sb.WriteString("</details>\n\n")

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString(fmt.Sprintf("*Generated by Pilot on %s*\n", time.Now().Format("2006-01-02 15:04:05")))

	return sb.String(), nil
}
