package replay

import (
	"fmt"
	"strings"
	"time"
)

// ExportHTMLReport generates a comprehensive HTML report with analysis
func ExportHTMLReport(recording *Recording, events []*StreamEvent, report *AnalysisReport) (string, error) {
	var sb strings.Builder

	sb.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
	sb.WriteString("<meta charset=\"UTF-8\">\n")
	sb.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
	sb.WriteString(fmt.Sprintf("<title>Execution Report: %s</title>\n", recording.ID))
	sb.WriteString("<style>\n")
	sb.WriteString(htmlReportStyles())
	sb.WriteString("</style>\n</head>\n<body>\n")

	// Header section
	sb.WriteString(renderHTMLHeader(recording))

	// Summary cards
	sb.WriteString(renderHTMLSummary(recording))

	// Token breakdown
	if report != nil && recording.TokenUsage != nil {
		sb.WriteString(renderHTMLTokenBreakdown(report))
	}

	// Phase timing chart
	if report != nil && len(report.PhaseAnalysis) > 0 {
		sb.WriteString(renderHTMLPhaseChart(report, recording.Duration))
	}

	// Tool usage
	if report != nil && len(report.ToolUsage) > 0 {
		sb.WriteString(renderHTMLToolUsage(report))
	}

	// Errors section
	if report != nil && len(report.Errors) > 0 {
		sb.WriteString(renderHTMLErrors(report))
	}

	// Timeline
	sb.WriteString(renderHTMLTimeline(events))

	// Footer
	sb.WriteString("<div class=\"footer\">\n")
	sb.WriteString(fmt.Sprintf("<p>Generated by Pilot v0.3.0 on %s</p>\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("</div>\n")

	sb.WriteString("</body>\n</html>")

	return sb.String(), nil
}

// Helper functions

func formatDuration(d time.Duration) string {
	if d < time.Minute {
		return fmt.Sprintf("%.1fs", d.Seconds())
	}
	if d < time.Hour {
		m := int(d.Minutes())
		s := int(d.Seconds()) % 60
		return fmt.Sprintf("%dm %ds", m, s)
	}
	h := int(d.Hours())
	m := int(d.Minutes()) % 60
	return fmt.Sprintf("%dh %dm", h, m)
}

func formatNumber(n int64) string {
	if n < 1000 {
		return fmt.Sprintf("%d", n)
	}
	if n < 1000000 {
		return fmt.Sprintf("%.1fK", float64(n)/1000)
	}
	return fmt.Sprintf("%.1fM", float64(n)/1000000)
}
