package architect

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/ylcn91/pilot/internal/pilotapi"
)

// dupBlock is a dupWindowK-line run of distinct significant statements used as a
// reusable copy-paste fixture across the duplication tests.
const dupBlock = `	a := compute(1)
	b := compute(2)
	c := a + b
	d := c * 3
	e := d - 1
	f := e / 2
`

// writeDupFile writes a .go file under dir whose body contains the given block
// inside a function, so the block's lines are significant (non-blank,
// non-comment) and form at least one duplication window.
func writeDupFile(t *testing.T, dir, name, block string) string {
	t.Helper()
	full := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	var sb strings.Builder
	sb.WriteString("package x\n\nfunc run() {\n")
	sb.WriteString(block)
	sb.WriteString("}\n")
	if err := os.WriteFile(full, []byte(sb.String()), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	return full
}

func TestDuplicationCollector_FlagsDuplicatedBlock(t *testing.T) {
	dir := t.TempDir()
	writeDupFile(t, dir, "first.go", dupBlock)
	writeDupFile(t, dir, "second.go", dupBlock)

	signals, err := NewDuplicationCollector().Collect(context.Background(), dir)
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	if len(signals) == 0 {
		t.Fatalf("expected at least one duplicate_block signal, got none")
	}
	s := signals[0]
	if s.Kind != kindDuplicateBlock {
		t.Errorf("Kind = %q, want %q", s.Kind, kindDuplicateBlock)
	}
	if s.File == "" {
		t.Errorf("File should be set, got empty")
	}
	if s.Weight <= 0 {
		t.Errorf("Weight = %v, want > 0", s.Weight)
	}
	if s.Risk != pilotapi.RiskMedium {
		t.Errorf("Risk = %q, want medium for a single duplicate across two files", s.Risk)
	}
}

func TestDuplicationCollector_HighRiskForThreeCopies(t *testing.T) {
	dir := t.TempDir()
	writeDupFile(t, dir, "a.go", dupBlock)
	writeDupFile(t, dir, "b.go", dupBlock)
	writeDupFile(t, dir, "c.go", dupBlock)

	signals, err := NewDuplicationCollector().Collect(context.Background(), dir)
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	if len(signals) == 0 {
		t.Fatalf("expected a duplicate_block signal for three copies, got none")
	}
	if signals[0].Risk != pilotapi.RiskHigh {
		t.Errorf("Risk = %q, want high for three copies", signals[0].Risk)
	}
	if signals[0].Weight < 3 {
		t.Errorf("Weight = %v, want >= 3 for three copies", signals[0].Weight)
	}
}

func TestDuplicationCollector_UniqueCodeNoSignals(t *testing.T) {
	dir := t.TempDir()
	writeDupFile(t, dir, "uniq1.go", `	a := compute(1)
	b := compute(2)
	c := a + b
	d := c * 3
	e := d - 1
	f := e / 2
`)
	writeDupFile(t, dir, "uniq2.go", `	g := compute(9)
	h := compute(8)
	i := g - h
	j := i * 7
	k := j + 6
	l := k / 5
`)

	signals, err := NewDuplicationCollector().Collect(context.Background(), dir)
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	if len(signals) != 0 {
		t.Fatalf("unique code must produce no signals; got %+v", signals)
	}
}

func TestDuplicationCollector_ExcludesTestFiles(t *testing.T) {
	dir := t.TempDir()
	writeDupFile(t, dir, "code.go", dupBlock)
	writeDupFile(t, dir, "code_dup_test.go", dupBlock)

	signals, err := NewDuplicationCollector().Collect(context.Background(), dir)
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	if len(signals) != 0 {
		t.Fatalf("a _test.go file must not pair with production code; got %+v", signals)
	}
}

func TestDuplicationCollector_ExcludesGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	writeDupFile(t, dir, "hand.go", dupBlock)

	gen := filepath.Join(dir, "gen.go")
	var sb strings.Builder
	sb.WriteString("// Code generated by tool. DO NOT EDIT.\n\npackage x\n\nfunc run() {\n")
	sb.WriteString(dupBlock)
	sb.WriteString("}\n")
	if err := os.WriteFile(gen, []byte(sb.String()), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}

	signals, err := NewDuplicationCollector().Collect(context.Background(), dir)
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	if len(signals) != 0 {
		t.Fatalf("a generated file must not contribute duplication; got %+v", signals)
	}
}

func TestDuplicationCollector_EmptyProjectNoSignals(t *testing.T) {
	dir := t.TempDir()
	signals, err := NewDuplicationCollector().Collect(context.Background(), dir)
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	if len(signals) != 0 {
		t.Fatalf("empty project must produce no signals; got %+v", signals)
	}
}

func TestDuplicationCollector_IgnoresNonGoFiles(t *testing.T) {
	dir := t.TempDir()
	for _, name := range []string{"a.txt", "b.md"} {
		var sb strings.Builder
		sb.WriteString(dupBlock)
		if err := os.WriteFile(filepath.Join(dir, name), []byte(sb.String()), 0o644); err != nil {
			t.Fatalf("write: %v", err)
		}
	}
	signals, err := NewDuplicationCollector().Collect(context.Background(), dir)
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	if len(signals) != 0 {
		t.Fatalf("non-go files must be ignored; got %+v", signals)
	}
}

func TestDuplicationCollector_DeterministicOrder(t *testing.T) {
	dir := t.TempDir()
	writeDupFile(t, dir, "z.go", dupBlock)
	writeDupFile(t, dir, "m.go", dupBlock)
	writeDupFile(t, dir, "a.go", dupBlock)

	first, err := NewDuplicationCollector().Collect(context.Background(), dir)
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	for i := 0; i < 3; i++ {
		again, err := NewDuplicationCollector().Collect(context.Background(), dir)
		if err != nil {
			t.Fatalf("Collect: %v", err)
		}
		if !reflect.DeepEqual(first, again) {
			t.Fatalf("signal order not stable across runs:\nfirst=%+v\nagain=%+v", first, again)
		}
	}
}

func TestNormalizeLine(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
		ok   bool
	}{
		{"blank", "   ", "", false},
		{"comment", "  // a note", "", false},
		{"collapses_ws", "  a   :=   b  ", "a := b", true},
		{"plain", "x := 1", "x := 1", true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, ok := normalizeLine(tc.in)
			if ok != tc.ok || got != tc.want {
				t.Errorf("normalizeLine(%q) = (%q,%v), want (%q,%v)", tc.in, got, ok, tc.want, tc.ok)
			}
		})
	}
}
