package autopilot

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/ylcn91/pilot/internal/adapters/github"
	"github.com/ylcn91/pilot/internal/memory"
	"github.com/ylcn91/pilot/internal/testutil"
)

func TestFeedbackLoop_IssueLabels(t *testing.T) {
	tests := []struct {
		name       string
		labels     []string
		wantLabels []string
	}{
		{
			name:       "default labels",
			labels:     []string{"pilot", "autopilot-fix"},
			wantLabels: []string{"pilot", "autopilot-fix"},
		},
		{
			name:       "custom labels",
			labels:     []string{"bug", "critical", "automated"},
			wantLabels: []string{"bug", "critical", "automated"},
		},
		{
			name:       "no labels",
			labels:     []string{},
			wantLabels: []string{},
		},
		{
			name:       "nil labels",
			labels:     nil,
			wantLabels: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			capturedLabels := []string{}

			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				if r.URL.Path == "/repos/owner/repo/issues" && r.Method == "POST" {
					var input github.IssueInput
					_ = json.NewDecoder(r.Body).Decode(&input)
					capturedLabels = input.Labels

					resp := github.Issue{Number: 110}
					w.WriteHeader(http.StatusCreated)
					_ = json.NewEncoder(w).Encode(resp)
					return
				}
				w.WriteHeader(http.StatusNotFound)
			}))
			defer server.Close()

			ghClient := github.NewClientWithBaseURL(testutil.FakeGitHubToken, server.URL)
			cfg := DefaultConfig()
			cfg.AutoCreateIssues = true
			cfg.IssueLabels = tt.labels

			fl := NewFeedbackLoop(ghClient, "owner", "repo", cfg)

			prState := &PRState{
				PRNumber: 42,
				HeadSHA:  "abc1234",
			}

			_, err := fl.CreateFailureIssue(
				context.Background(),
				prState,
				FailureCIPreMerge,
				nil,
				"",
				0,
			)

			if err != nil {
				t.Fatalf("CreateFailureIssue() error = %v", err)
			}

			if len(capturedLabels) != len(tt.wantLabels) {
				t.Errorf("labels = %v, want %v", capturedLabels, tt.wantLabels)
			}
		})
	}
}

func TestFeedbackLoop_BodyContainsAutoGeneratedNote(t *testing.T) {
	capturedBody := ""

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/repos/owner/repo/issues" && r.Method == "POST" {
			var input github.IssueInput
			_ = json.NewDecoder(r.Body).Decode(&input)
			capturedBody = input.Body

			resp := github.Issue{Number: 111}
			w.WriteHeader(http.StatusCreated)
			_ = json.NewEncoder(w).Encode(resp)
			return
		}
		w.WriteHeader(http.StatusNotFound)
	}))
	defer server.Close()

	ghClient := github.NewClientWithBaseURL(testutil.FakeGitHubToken, server.URL)
	cfg := DefaultConfig()
	cfg.AutoCreateIssues = true

	fl := NewFeedbackLoop(ghClient, "owner", "repo", cfg)

	prState := &PRState{
		PRNumber: 42,
		HeadSHA:  "abc1234",
	}

	_, err := fl.CreateFailureIssue(
		context.Background(),
		prState,
		FailureCIPreMerge,
		nil,
		"",
		0,
	)

	if err != nil {
		t.Fatalf("CreateFailureIssue() error = %v", err)
	}

	// Should contain auto-generated note
	if !strings.Contains(capturedBody, "auto-generated by Pilot autopilot") {
		t.Error("body should contain auto-generated note")
	}
}

func TestFeedbackLoop_IssueBody_BranchMetadata(t *testing.T) {
	capturedBody := ""

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/repos/owner/repo/issues" && r.Method == "POST" {
			var input github.IssueInput
			_ = json.NewDecoder(r.Body).Decode(&input)
			capturedBody = input.Body

			resp := github.Issue{Number: 112}
			w.WriteHeader(http.StatusCreated)
			_ = json.NewEncoder(w).Encode(resp)
			return
		}
		w.WriteHeader(http.StatusNotFound)
	}))
	defer server.Close()

	ghClient := github.NewClientWithBaseURL(testutil.FakeGitHubToken, server.URL)
	cfg := DefaultConfig()
	cfg.AutoCreateIssues = true

	fl := NewFeedbackLoop(ghClient, "owner", "repo", cfg)

	prState := &PRState{
		PRNumber:    42,
		HeadSHA:     "abc1234567890",
		IssueNumber: 10,
		BranchName:  "pilot/GH-10",
	}

	_, err := fl.CreateFailureIssue(
		context.Background(),
		prState,
		FailureCIPreMerge,
		[]string{"lint"},
		"",
		0,
	)

	if err != nil {
		t.Fatalf("CreateFailureIssue() error = %v", err)
	}

	// Should contain human-readable branch reference
	if !strings.Contains(capturedBody, "**Branch**: pilot/GH-10") {
		t.Error("body should contain branch reference in context section")
	}

	// Should contain machine-readable metadata comment with branch, PR number, and iteration (GH-1267, GH-1566)
	if !strings.Contains(capturedBody, "<!-- autopilot-meta branch:pilot/GH-10 pr:42 iteration:0 -->") {
		t.Error("body should contain autopilot-meta comment with branch, PR number, and iteration")
	}
}

func TestFeedbackLoop_IssueBody_NoBranchMetadataWhenEmpty(t *testing.T) {
	capturedBody := ""

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/repos/owner/repo/issues" && r.Method == "POST" {
			var input github.IssueInput
			_ = json.NewDecoder(r.Body).Decode(&input)
			capturedBody = input.Body

			resp := github.Issue{Number: 113}
			w.WriteHeader(http.StatusCreated)
			_ = json.NewEncoder(w).Encode(resp)
			return
		}
		w.WriteHeader(http.StatusNotFound)
	}))
	defer server.Close()

	ghClient := github.NewClientWithBaseURL(testutil.FakeGitHubToken, server.URL)
	cfg := DefaultConfig()
	cfg.AutoCreateIssues = true

	fl := NewFeedbackLoop(ghClient, "owner", "repo", cfg)

	prState := &PRState{
		PRNumber: 42,
		HeadSHA:  "abc1234567890",
		// BranchName intentionally empty
	}

	_, err := fl.CreateFailureIssue(
		context.Background(),
		prState,
		FailureCIPreMerge,
		[]string{"lint"},
		"",
		0,
	)

	if err != nil {
		t.Fatalf("CreateFailureIssue() error = %v", err)
	}

	// Should NOT contain branch metadata when BranchName is empty
	if strings.Contains(capturedBody, "autopilot-meta") {
		t.Error("body should not contain autopilot-meta when BranchName is empty")
	}
	if strings.Contains(capturedBody, "**Branch**") {
		t.Error("body should not contain Branch field when BranchName is empty")
	}
}

func TestFeedbackLoop_GenerateBody_WithPatterns(t *testing.T) {
	ghClient := github.NewClient(testutil.FakeGitHubToken)
	cfg := DefaultConfig()
	cfg.AutoCreateIssues = true
	fl := NewFeedbackLoop(ghClient, "owner", "repo", cfg)

	prState := &PRState{
		PRNumber: 42,
		HeadSHA:  "abc1234567890",
	}

	// Test with patterns passed directly to generateBody
	patterns := []*memory.CrossPattern{
		{Title: "Missing import", Description: "Always check imports after refactoring", Confidence: 0.85},
		{Title: "Test timeout", Description: "Increase timeout for integration tests", Confidence: 0.92},
	}

	body := fl.generateBody(prState, FailureCIPreMerge, []string{"build"}, "Error: build failed", 0, patterns)

	if !strings.Contains(body, "Known Patterns") {
		t.Error("body should contain Known Patterns section when patterns provided")
	}
	if !strings.Contains(body, "Missing import") {
		t.Error("body should contain pattern title 'Missing import'")
	}
	if !strings.Contains(body, "85%") {
		t.Error("body should contain pattern confidence as percentage")
	}
	if !strings.Contains(body, "Test timeout") {
		t.Error("body should contain pattern title 'Test timeout'")
	}
	if !strings.Contains(body, "92%") {
		t.Error("body should contain pattern confidence as percentage")
	}
}

func TestFeedbackLoop_GenerateBody_NoPatterns(t *testing.T) {
	ghClient := github.NewClient(testutil.FakeGitHubToken)
	cfg := DefaultConfig()
	cfg.AutoCreateIssues = true
	fl := NewFeedbackLoop(ghClient, "owner", "repo", cfg)

	prState := &PRState{
		PRNumber: 42,
		HeadSHA:  "abc1234567890",
	}

	// Empty patterns slice — no Known Patterns section
	body := fl.generateBody(prState, FailureCIPreMerge, []string{"build"}, "", 0, nil)

	if strings.Contains(body, "Known Patterns") {
		t.Error("body should NOT contain Known Patterns section when no patterns")
	}
}
